# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${postgre_password}
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes: 
      - "./pgData:/var/lib/postgresql/data"
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - "./redis/redis.conf:/usr/local/etc/redis/redis.conf"
      - "./redis/logs/:/var/log/redis/"
      - "./redis/:/var/lib/redis/"
    command: 
      /bin/bash -c "redis-server /usr/local/etc/redis/redis.conf"
  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    ports: 
      - "8001:8080"
    volumes: 
      - "./jenkins/:/var/jenkins_home"
